version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    ports:
      - "4010:4010"
    env_file:
      - ./.env
  web:
    build:
      context: resources
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - node