version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - .:/superhero
    ports:
      - "4010:4010"
    env_file:
      - ./.env